<?php

namespace App\Services;

use App\Models\MembershipType;
use App\Models\Payment;
use App\Models\Profit;
use App\Models\User;

class ProfitDistributionService
{
    public function __construct(private readonly AffiliateTreeService $affiliateTreeService)
    {
    }

    public function distributeForApprovedPayment(Payment $payment, MembershipType $membershipType): void
    {
        if (strtolower((string) $membershipType->name) !== 'customer') {
            return;
        }

        $payment->loadMissing('user');
        $buyer = $payment->user;

        if (! $buyer instanceof User) {
            return;
        }

        $sponsors = $this->affiliateTreeService->sponsorsByLevel(
            $buyer,
            (int) config('affiliates.max_sponsor_levels', 3)
        );

        /** @var array<int, float|int|string> $distribution */
        $distribution = (array) config('affiliates.profit_distribution', []);

        foreach ($sponsors as $row) {
            $level = (int) $row['level'];
            /** @var User $sponsor */
            $sponsor = $row['user'];

            $percent = (float) ($distribution[$level] ?? 0);
            if ($percent <= 0) {
                continue;
            }

            $amount = round(((float) $payment->amount) * $percent, 2);
            if ($amount <= 0) {
                continue;
            }

            $defaultBank = $sponsor->defaultUserBank()->first();
            if ($defaultBank === null) {
                continue;
            }

            Profit::query()->create([
                'user_id' => $sponsor->id,
                'user_bank_id' => $defaultBank->id,
                'period_month' => now()->startOfMonth()->toDateString(),
                'source_payment_id' => $payment->id,
                'source_user_id' => $buyer->id,
                'source_level' => $level,
                'amount' => $amount,
                'state' => 'pending',
                'detail' => sprintf(
                    'Pending profit generated by payment #%d from user #%d at level %d (%.2f%%).',
                    $payment->id,
                    $buyer->id,
                    $level,
                    $percent * 100
                ),
            ]);

            $sponsor->increment('commission_balance', $amount);
        }
    }
}
