<?php

namespace App\Services;

use App\Models\MembershipType;
use App\Models\Payment;
use App\Models\Profit;
use App\Models\User;
use Illuminate\Support\Str;

class ProfitDistributionService
{
    public function __construct(private readonly AffiliateTreeService $affiliateTreeService)
    {
    }

    public function distributeForApprovedPayment(Payment $payment, MembershipType $membershipType): void
    {
        if (strtolower((string) $membershipType->name) !== 'customer') {
            return;
        }

        $payment->loadMissing('user');
        $buyer = $payment->user;

        if (! $buyer instanceof User) {
            return;
        }

        $isFirstApprovedPayment = (int) Payment::query()
            ->where('user_id', $buyer->id)
            ->where('state', 'approved')
            ->count() === 1;

        $sponsors = $this->affiliateTreeService->sponsorsByLevel(
            $buyer,
            (int) config('affiliates.max_sponsor_levels', 7)
        );

        /** @var array<int, float|int|string|array<string, float|int|string>> $distribution */
        $distribution = (array) config('affiliates.level_commissions', []);

        foreach ($sponsors as $row) {
            $level = (int) $row['level'];
            /** @var User $sponsor */
            $sponsor = $row['user'];

            if (! $this->canReceiveCommissionsAtLevel($sponsor, $level)) {
                continue;
            }

            $amount = $this->resolveLevelAmount($distribution, $level, $isFirstApprovedPayment);
            if ($amount <= 0) {
                continue;
            }

            $defaultBank = $sponsor->defaultUserBank()->first();

            Profit::query()->create([
                'user_id' => $sponsor->id,
                'user_bank_id' => $defaultBank?->id,
                'period_month' => now()->startOfMonth()->toDateString(),
                'source_payment_id' => $payment->id,
                'source_user_id' => $buyer->id,
                'source_level' => $level,
                'amount' => $amount,
                'state' => 'pending',
                'detail' => sprintf(
                    'Pending profit generated by payment #%d from user #%d at level %d (%s).',
                    $payment->id,
                    $buyer->id,
                    $level,
                    $isFirstApprovedPayment ? 'new activation' : 'renewal/reactivation'
                ),
            ]);

            $sponsor->increment('commission_balance', $amount);
        }
    }

    private function canReceiveCommissionsAtLevel(User $sponsor, int $level): bool
    {
        if ($sponsor->hasRole('admin')) {
            return false;
        }

        $sponsor->loadMissing('membership.membershipType');

        $membership = $sponsor->membership;
        if ($membership === null || (string) $membership->status !== 'active') {
            return false;
        }

        $typeName = strtolower((string) ($membership->membershipType?->name ?? ''));
        if ($typeName === '' || $typeName === 'free') {
            return false;
        }

        return $this->resolveUnlockedLevelByTypeName($typeName) >= $level;
    }

    /**
     * @param array<int, float|int|string|array<string, float|int|string>> $distribution
     */
    private function resolveLevelAmount(array $distribution, int $level, bool $isFirstApprovedPayment): float
    {
        $levelConfig = $distribution[$level] ?? 0;

        if ($level === 1 && is_array($levelConfig)) {
            $key = $isFirstApprovedPayment ? 'new' : 'renewal';

            return round((float) ($levelConfig[$key] ?? 0), 2);
        }

        return round((float) $levelConfig, 2);
    }

    private function resolveUnlockedLevelByTypeName(string $typeName): int
    {
        $normalized = Str::lower($typeName);

        return match ($normalized) {
            'customer' => 1,
            'beginner' => 1,
            'constructor' => 2,
            'explorer' => 3,
            'professional', 'proffesional' => 4,
            'elite' => 5,
            'master' => 6,
            'legend' => 7,
            default => 0,
        };
    }
}
